name: airdrop_flow
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.16.0

  # State Management
  flutter_riverpod: ^2.4.0

  # Networking
  http: ^1.2.1
  url_launcher: ^6.3.1

  # Utilitas
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  local_auth: ^2.2.0
  shared_preferences: ^2.2.3
  flutter_dotenv: ^5.1.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env