// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT-iwXCHw1ZIGgqRJ9si2yqOEfGobkJzQ',
    appId: '1:298395940261:web:aeac0669b669adbe19244c',
    messagingSenderId: '298395940261',
    projectId: 'airdrop-flow',
    authDomain: 'airdrop-flow.firebaseapp.com',
    storageBucket: 'airdrop-flow.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmOsvLzQJKHsuTfka138o5jS2FlcqsdOo',
    appId: '1:298395940261:android:c7a6cb16cea8950119244c',
    messagingSenderId: '298395940261',
    projectId: 'airdrop-flow',
    storageBucket: 'airdrop-flow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF84wiBdTA5e7PeM5vjzTBB4Jbl5PKfKU',
    appId: '1:298395940261:ios:d4e2e6032e88d88319244c',
    messagingSenderId: '298395940261',
    projectId: 'airdrop-flow',
    storageBucket: 'airdrop-flow.firebasestorage.app',
    iosBundleId: 'com.example.airdroptracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF84wiBdTA5e7PeM5vjzTBB4Jbl5PKfKU',
    appId: '1:298395940261:ios:d4e2e6032e88d88319244c',
    messagingSenderId: '298395940261',
    projectId: 'airdrop-flow',
    storageBucket: 'airdrop-flow.firebasestorage.app',
    iosBundleId: 'com.example.airdroptracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT-iwXCHw1ZIGgqRJ9si2yqOEfGobkJzQ',
    appId: '1:298395940261:web:2f6f38c4dff6098c19244c',
    messagingSenderId: '298395940261',
    projectId: 'airdrop-flow',
    authDomain: 'airdrop-flow.firebaseapp.com',
    storageBucket: 'airdrop-flow.firebasestorage.app',
  );
}
